import numpy as np
import pandas as pd

def toGPX(pathX, pathY):
	GPXFile = open("optimalRouteGPX.gpx", "w")
	GPXFile.write('<?xml version="1.0" encoding="UTF-8"?>\n')
	GPXFile.write('<gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1" creator="Franklin Sun" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">\n')
	GPXFile.write('<rte>\n')
	GPXFile.write('<name>Optimal path generated by pocketSherpa</name>\n')

	for coord in range(len(pathX)):
		GPXFile.write('<rtept lon="' + str(pathX[coord]) + '" lat="' + str(pathY[coord]) + '">\n')
		GPXFile.write('<ele>0</ele>\n')
		GPXFile.write('</rtept>\n')

	GPXFile.write('</rte>\n')
	GPXFile.write('</gpx>')